### ISSUE TITLE
可以release一个安装的版本？

### ISSUE THREAD

**Issue by wjx0912** [d100000/Watcher#1]
谢谢

**Comment by d100000** [comment]
Beta 版安装包下载地址，同时可以一键卸载：http://api.bobdong.cn/public/static/Win/Watcher守望者.exe

**Comment by d100000** [comment]
新版带自动更新功能的将会在8月4号左右提交，到时候下载地址不变，直接重新下载覆盖安装就行了，之后软件每次启动都可以自动更新到最新的版本了
